package SWIFT;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Robot;
import java.awt.event.KeyEvent;

public class Serve extends javax.swing.JFrame {

    public Serve() {
        minimizeCommand();
        initComponents();
		
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
	@Override
	public void mouseExited(java.awt.event.MouseEvent evt) {
		jLabel9.setVisible(false);
		repaint();
            }        
	});

        
        jLabel9.setVisible(false);
        loading.setVisible(false); // The image that shows for 5 seconds
    
    // PREVENT the hover label from stealing mouse clicks
        jLabel9.setFocusable(false);
        
        getContentPane().setComponentZOrder(btnEnter, 0);
        getContentPane().setComponentZOrder(loading, 0);
        getContentPane().setComponentZOrder(jLabel9, 1);

        
        // 2. Custom code (Safe to edit here)
        // Sets background to transparent - works best with Undecorated frames
        this.setBackground(new Color(0, 0, 0, 0)); 
        this.setLocationRelativeTo(null); 
    }
    
    private void minimizeCommand() {
        try {
            Robot robot = new Robot();
            // Simulates Windows + D to show desktop and hide NetBeans
            robot.keyPress(KeyEvent.VK_WINDOWS);
            robot.keyPress(KeyEvent.VK_D);
            robot.keyRelease(KeyEvent.VK_D);
            robot.keyRelease(KeyEvent.VK_WINDOWS);
        } catch (AWTException e) {
            // If Robot fails, we log it but allow the splash to continue
            System.err.println("Could not minimize: " + e.getMessage());
        }
    }

    public void startAnimation() {
        new Thread(() -> {
            try {
                // Fade In Logic - This makes the whole window appear smoothly
                for (float i = 0f; i <= 1.0f; i += 0.02f) {
                    this.setOpacity(i);
                    Thread.sleep(30); 
                }
                // Note: We removed the Thread.sleep(60000) and dispose() 
                // because we want the user to click a button instead.
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnter = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnter.setContentAreaFilled(false);
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnterMouseEntered(evt);
            }
        });
        getContentPane().add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/source.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 20, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Foods.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 300, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Food.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 300, 260));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Serve.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 190, 80));

        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LoadingF.gif"))); // NOI18N
        getContentPane().add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 360, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Frame1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 880, 530));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Serve.gif"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 190, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                      
                    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {                                      
                        // Disable the button so the user doesn't click it multiple times
                        btnEnter.setEnabled(false);

                        new Thread(() -> {
                            try {
                                java.awt.EventQueue.invokeLater(() -> {
                                    loading.setVisible(true); // Assuming jLabel12 is the image you want to show
                                    repaint();
                                });

                                // 3. Show that image for another 5 seconds
                                Thread.sleep(3000);

                                // 4. Finally, transition to the next form
                                java.awt.EventQueue.invokeLater(() -> {
                                    this.dispose();
                                    new LoginForm().setVisible(true);
                                });

                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                        }).start();
                    }                                    

			private void btnEnterMouseEntered(java.awt.event.MouseEvent evt) {                                      
				// Explicitly set cursor on the button AND the parent container if needed
				btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
				
				// Action: Show Hover Image
				jLabel9.setVisible(true);
				
				// Ensure the button stays on top after visibility changes
				getContentPane().setComponentZOrder(btnEnter, 0);
				
				this.repaint();
			}                                    
			
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Serve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Serve s = new Serve();
            s.setOpacity(0f); 
            s.setVisible(true);
            s.startAnimation();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel loading;
    // End of variables declaration//GEN-END:variables
}